name: Nix checks

on:
  pull_request:
  push:
    branches: [main, test-ci]

jobs:
  check-nix:
    runs-on: ubicloud-standard-2
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      # - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check health of flake.lock
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
